<a href="https://colab.research.google.com/github/Rixxi21/Dimensions-NumPy/blob/main/Dimensiones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [ ]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [ ]:
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [ ]:
matriz = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(matriz)
matriz.ndim

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


3

In [ ]:
tensor = np.array([[[1,2,3], [4,5,6], [7,8,9]],[[6,5,4,],[3,2,1],[9,8,7]]])
print(tensor)
tensor.ndim

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[6 5 4]
  [3 2 1]
  [9 8 7]]]


3

## Agregar o eliminar dimensiones

In [ ]:
vector = np.array([1,2,3],ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [ ]:
expand = np.expand_dims(np.array([1,2,3]),axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [ ]:
expand = np.expand_dims(np.array([1,2,3]),axis=1)
print(expand)
expand.ndim

[[1]
 [2]
 [3]]


2

In [ ]:
print(vector, vector.ndim)
vector2 = np.squeeze(vector)
print(vector2, vector2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


In [ ]:
tensor = np.array([4,5,6],ndmin=5)
print(tensor)
tensor.ndim

[[[[[4 5 6]]]]]


5

Reto

In [ ]:
tensor = np.array([[[[[4,5,6],[1,4,3],[5,8,2]],[[4,3,1],[7,1,9],[2,9,3]]]]])
print(tensor)
tensor.ndim

[[[[[4 5 6]
    [1 4 3]
    [5 8 2]]

   [[4 3 1]
    [7 1 9]
    [2 9 3]]]]]


5

In [ ]:
print(tensor, tensor.ndim)
tensor2 = np.squeeze(tensor)
print(vector2, tensor2.ndim)

[[[[[4 5 6]
    [1 4 3]
    [5 8 2]]

   [[4 3 1]
    [7 1 9]
    [2 9 3]]]]] 5
[1 2 3] 3
